spring:
  application:
    name: spring_jdbc

#  # Datasource connection
#  datasource:
#    username: root
#    password: Pkswain@123
#    url: "jdbc:mysql://localhost:3306/student_db" # jdbc:mysql:// - where the DB is located & which DB to call , localhost:3306 - hostname/IP adress + associated hostname ,/student_db" - The DB name
#    hikari:
#      maximum-pool-size: 10 # maximum number of connection managed by the pool
#      minimum-idle: 5       # maximum number of idle connections the pool attempt to main
#      connection-timeout: 30000 # Maximum  waiting time for a connection before failure
#      idle-timeout: 60000  # this much time a connection can stay idle before removal
#      max-lifetime: 180000 # maximum life time of a pooled connection
#
#
#


